import Head from 'next/head'
import Image from 'next/image'
import NavBar from '@/components/NavBar'
import { useEffect, useRef, useState } from 'react'
export default function Home() {
  const [visible, setVisible] = useState(false)
  const menuRef = useRef()
  const openMenu = () => {
    setVisible(!visible)
  }
  useEffect(() => {
    console.log("Effect ran")
    const handleClick = (event) => {
      if (menuRef.current && !menuRef.current.contains(event.target) && event.target.tagName !== 'HTML') {
        setVisible(false)
      }
    }
    document.addEventListener('mousedown', handleClick)
    return () => {
      document.removeEventListener('mousedown', handleClick)
    }
  }, [menuRef])
  return (
    <div className='bg-blackish py-5 w-full h-full'>
      <Head>
        <title>codefusion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <div className='md:max-w-5xl md:mx-auto xl:max-w-screen-xl'>
            <div className='flex justify-between px-3'>
              <Image
                src="/svg-export/logo.svg"
                className='h-auto'
                width={140}
                height={150}
                alt="logo"
              />
              <div className='relative' ref={menuRef}>
                <button
                  className='border px-4 py-2 rounded-md cursor-pointer
                focus:outline-none focus:ring-1 focus:ring-offset-blue-700
                lg:hidden'
                  onClick={openMenu}
                >
                  <div className='sm:w-16 sm:flex sm:justify-around
                sm:align-middle'>
                    <p
                      className='hidden font-bold tracking-wide
                text-white sm:inline text-xs'
                    >
                      MENU
                    </p>
                    <Image
                      src="/svg-export/bars.svg"
                      className='h-auto'
                      width={15} height={13} alt="logo"
                    />
                  </div>
                </button>
                <div className='hidden lg:inline'>
                  <NavBar />
                </div>
                <div className='lg:hidden'>
                  {visible && <NavBar />}
                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main className='mt-28'>
        {/* <Image className='h-auto' src={'/svg-export/svgexport-25.svg'} height={150} width={250} alt=""/> */}
        <section>
          <div className='flex flex-col items-center'>
            <div
              className='flex justify-around text-white
            text-sm align-middle w-60 border rounded-3xl py-1
            border-orangish '
            >
              <div className='border border-orangish rounded-3xl px-2 bg-orangish'>
                <p>NEW</p>
              </div>
              <p>Business Plans are here! →</p>
            </div>
            <div className='mt-2 text-center'>
              <h1 className='mb-4 text-7xl font-bold text-whitish'>The Better Way to Meeting</h1>
              <h2 className='mb-4 text-3xl text-grayish'>
                Get your team on the same page inside online meeting rooms
                with collaborative productivity tools.
              </h2>
            </div>
            <div className='w-full'>
              <form className='max-w-xs mx-auto flex flex-col mt-4'>
                <input
                  className='border-2 focus:outline-none focus:ring
                focus:ring-activeblue text-lg p-3 rounded-md
                '
                  type="text"
                  placeholder='Enter a name for your room'
                />
                <button className='bg-bluish text-white text-lg
                font-semibold py-3 mt-2 rounded-md '
                  type='submit'
                >
                  Get A Room →
                </button>
              </form>
            </div>
          </div>
          <div className='mt-14'>
            <Image className='w-auto' src={"/svg-export/plateau.svg"} height={200} width={120} alt="" />
          </div>
        </section>
        <section id='features' className='pt-24 flex flex-col bg-white items-center'>
          <div className='flex px-2 py-2 items-center rounded-full bg-yellowish'>
            <div className='rounded-full bg-white p-2'>
              <Image className='h-auto' src={'/svg-export/edit-icon.svg'} height={20} width={20} alt='' />
            </div>
            <p className='px-2 text-orange-600 font-bold'>Whiteboard</p>
          </div>
          <div className='mt-4 text-center text-5xl font-extrabold'>
            <h1>Scribble, <span className='block'>Sketch, Draw</span>  & Diagram </h1>
          </div>
          <div className='mt-4 text-center text-xl text-blacklike'>
            <div>
              Lay out your plans, brainstorm
              <span className='block'>some ideas, or annotate an</span>
              <span className='block'>imported document or </span>
              screenshot.
            </div>
            <div className='mt-4 uppercase text-sm font-semibold text-orangish'>
              <div className='flex flex-row items-center'>
                <Image className='h-auto' src={'/svg-export/multidirection.svg'} height={20} width={17} alt='' />
                <p className='px-3 py-2'>Infinite, Multi-Directional Canvas </p>
              </div>
              <div className='pl-6 flex flex-row'>
                <Image className='h-auto' src={'/svg-export/adobe.svg'} height={10} width={15} alt='' />
                <p className='px-3'>Import PDFs and Other Docs</p>
              </div>
              <div className='flex flex-row'>
                <Image className='h-auto' src={'/svg-export/camera.svg'} height={20} width={15} alt='' />
                <p className='px-3 py-2'>Screenshot and Upload Your Video Feed </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
